### ISSUE TITLE
我有问题

### ISSUE THREAD

**Issue by Hi-Rube** [CFC-STUDY/JS-Study#12]
什么问题

**Comment by Irelylnny** [comment]
董老师 - - 
express要不要安
是只安好nodejs和npm就可以了吗
你要不要讲一下bower怎么用。。。

**Comment by Hi-Rube** [comment]
@Irelylnny  这些后面都要讲哇，  先安装下nodemon吧~   npm install -g nodemon

**Comment by niugeshenhua** [comment]
董叔 人呢。。。。

**Comment by Hi-Rube** [comment]
@niugeshenhua 明天继续讲
